apiVersion: v1
kind: Pod
metadata:
  name: in-class
spec:
#  activeDeadlineSeconds: 1800  # Pod terminates after 30 min
  securityContext:
    runAsUser: 260433 # run id command in terminal to get your UID
    runAsGroup: 50038
  containers:
    - name: in-class
      image: ghcr.io/tford9/template_kubernetes:main  # image name
      resources:
        requests: # minimum resources
          memory: "16Gi"
          cpu: "8"
        limits: # maximum resources
          memory: "24Gi"
          cpu: "16"
      volumeMounts:
      - name: home
        mountPath: "/app"
      command: ["/bin/sh"]
      stdin: true
      tty: true
  volumes:
  - name: home
    nfs:
      server: 128.239.56.166
      path: /sciclone/home/twford/repos/today_in_class